{{- if .Values.global.istio.enabled }}
---
# EnvoyFilter to fix Apache HttpClient 5.4+ upgrade header issue
# Reference: https://github.com/istio/istio/issues/53239
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: remove-upgrade-header
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "petclinic.labels" . | nindent 4 }}
spec:
  workloadSelector:
    labels:
      app.kubernetes.io/part-of: petclinic
  configPatches:
  - applyTo: NETWORK_FILTER
    match:
      context: SIDECAR_OUTBOUND
      listener:
        portNumber: 8761
        filterChain:
          filter:
            name: envoy.filters.network.http_connection_manager
    patch:
      operation: MERGE
      value:
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          upgrade_configs: []
{{- end }}

