{{- if .Values.global.istio.enabled }}
---
# EnvoyFilter to fix Apache HttpClient 5.x upgrade issues with Eureka
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: eureka-upgrade-fix
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "petclinic.labels" . | nindent 4 }}
spec:
  workloadSelector:
    labels:
      app.kubernetes.io/part-of: petclinic
  configPatches:
    # Disable upgrade for outbound traffic to discovery-server
    - applyTo: CLUSTER
      match:
        context: SIDECAR_OUTBOUND
        cluster:
          service: discovery-server.{{ .Values.global.namespace }}.svc.cluster.local
      patch:
        operation: MERGE
        value:
          upstream_http_protocol_options:
            auto_sni: true
          typed_extension_protocol_options:
            envoy.extensions.upstreams.http.v3.HttpProtocolOptions:
              "@type": type.googleapis.com/envoy.extensions.upstreams.http.v3.HttpProtocolOptions
              explicit_http_config:
                http_protocol_options:
                  accept_http_10: true
{{- end }}


