apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.global.namespace }}
  labels:
    {{- include "petclinic.labels" . | nindent 4 }}
    {{- if .Values.global.istio.enabled }}
    istio-injection: enabled
    {{- end }}

